# Update commit status in GitHub
updateCommitStatus: &UPDATE_COMMIT_STATUS
  onStart:
    - update_commit_status jfrog_cli_plugins_reg --context "$step_name"
  onComplete:
    - update_commit_status jfrog_cli_plugins_reg --context "$step_name"

resources:
  - name: jfrog_cli_plugins_reg
    type: GitRepo
    configuration:
      path: Or-Gabay/jfrog-cli-plugins-reg
      gitProvider: or_cli_github
      buildOn:
        commit: false
        pullRequestCreate: true
      branches:
        include: master
      files:
        include: ^plugins\/.+
pipelines:
  - name: plugin_pr_validation
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog-ecosystem-integration-env
            tag: 1.0.0
      environmentVariables:
        readOnly:
          #GOPROXY: https://gocenter.io
          CI: "true"
    steps:
      - name: pull_request_includes_only_plugins_yml
        type: Bash
        configuration:
          integrations:
            - name: or_github
          inputResources:
            - name: jfrog_cli_plugins_reg
        execution:
          <<: *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_jfrog_cli_plugins_reg_resourcePath/pipelinesScripts/pluginsvalidation
            - go get gopkg.in/yaml.v2
            - go run yaml.go Extension
      - name: valid_plugins_yml_structure
        type: Bash
        configuration:
          integrations:
            - name: or_github
          inputResources:
            - name: jfrog_cli_plugins_reg
          inputSteps:
            - name: pull_request_includes_only_plugins_yml
        execution:
          <<: *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_jfrog_cli_plugins_reg_resourcePath/pipelinesScripts/pluginsvalidation
            - go get gopkg.in/yaml.v2
            - go run yaml.go Structure
      - name: plugins_test_passed
        type: Bash
        configuration:
          integrations:
            - name: or_github
          inputResources:
            - name: jfrog_cli_plugins_reg
          inputSteps:
            - name: valid_plugins_yml_structure
        execution:
          <<: *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_jfrog_cli_plugins_reg_resourcePath/pipelinesScripts/pluginsvalidation
            - go get gopkg.in/yaml.v2
            - go run yaml.go Tests